print("Enter a word")
str1 = input()
print("Enter a number of letters that word consists of")
number_of_letters = int(input())
print("Enter a letter that you want to find an index")
index = input()
bool1 = number_of_letters == len(str1)
index = str1.find(index)
print(bool1)
print(index)